on:
    schedule:
        - cron: '*/2 * * * *'
jobs:
    display_date:
        runs_on: ubuntu-latest
        steps:
            - name: Echo current time
              run: echo "The current server Time is $(date)"
        
